modLoader = "javafml"
loaderVersion = "[47,)"
license = "LGPL-3.0-only"

[[mods]]
modId = "doapi"
version = "${version}"
displayName = "Lets Do Api"
authors = "Cristelknight, BaumeisterJO"
logoFile = "pack.png"
description = '''
This is an API for the Let's do mods
'''

[[mods]]
modId = "terraform"
version = "7.0.1"
displayName = "Terraform Wood Api Reforged"
credits = "Prospector, coderbot16, TerraformersMC, for making the original"
authors = "Cristelknight999"
description = '''
Terraform Wood Api, but for forge
'''

[[dependencies.doapi]]
modId = "forge"
mandatory = true
versionRange = "[47.0.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.doapi]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.doapi]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"